### ISSUE TITLE
socks proxy connection failed

### ISSUE THREAD

**Issue by shaoweigege** [io-developer/php-whois#56]
**PHP-Whois version**: current stable release

**PHP version**: 7.2.0

**Description**  
I am usesing this package to query whois data via proxy socks5 and some of the domains response errors.

for example , most of the new gtlds such as .xyz .run .ltd .fun etc  proxy connection failed 
some cctld such as .gs .cx  proxy failed 

PHP Fatal error:  Uncaught Iodev\Whois\Exceptions\ConnectionException: Can't complete SOCKS5 connection to 2620:0115:3000:5003:0000:0000:0000:0132:43. (8) in /opt/vendor/io-developer/php-whois/src/Iodev/Whois/Loaders/CurlLoader.php:107
Stack trace:
#0 /opt/vendor/io-developer/php-whois/src/Iodev/Whois/Modules/Tld/TldModule.php(165): Iodev\Whois\Loaders\CurlLoader->loadText('whois.donuts.co', '404.run\r\n')
#1 /opt/vendor/io-developer/php-whois/src/Iodev/Whois/Modules/Tld/TldModule.php(210): Iodev\Whois\Modules\Tld\TldModule->loadResponse(Object(Iodev\Whois\Modules\Tld\TldServer), '404.run', false, 'whois.donuts.co')
#2 /opt/vendor/io-developer/php-whois/src/Iodev/Whois/Modules/Tld/TldModule.php(185): Iodev\Whois\Modules\Tld\TldModule->loadParsedTo(NULL, NULL, Object(Iodev\Whois\Modules\Tld\TldServer), '404.run', false, NULL, Object(Iodev\Whois\Exceptions\ConnectionException))
#3 /opt/vendor/io-developer/php-whois/src/Iodev/Whois/Modules/Tld/TldModule.php(148): Iodev\Whois\Modules\Tld\TldModule->loadDomainData('404.run', Array) in /opt/vendor/io-developer/php-whois/src/Iodev/Whois/Loaders/CurlLoader.php on line 107

**How to reproduce**  

require 'vendor/autoload.php';
use Iodev\Whois\Loaders\CurlLoader;
use Iodev\Whois\Whois;
$loader = new CurlLoader();
$loader->replaceOptions([
    CURLOPT_PROXYTYPE => CURLPROXY_SOCKS5,
    CURLOPT_PROXY => "some socks5 ip and port"
]);
$whois = Whois::create($loader);
var_dump([
    '404.run' => $whois->loadDomainInfo('404.run')
]);

**Possible Solution**  

**Additional context**

**Comment by io-developer** [comment]
Looks like you have bad proxy.

I used SOCKS5 proxy on private VPS and cannot confirm:

* Added to Iodev/Whois/Configs/module.tld.servers.json
![image](https://user-images.githubusercontent.com/6779324/57571389-40656480-7416-11e9-86d3-53ebebc2e67e.png)

* Used this code:
```php
<?php

use Iodev\Whois\Loaders\CurlLoader;
use Iodev\Whois\Whois;

require_once 'vendor/autoload.php';

$loader = new CurlLoader();
$loader->replaceOptions([
    CURLOPT_PROXYTYPE => CURLPROXY_SOCKS5,
    CURLOPT_PROXY => "xxxx:xx",
    CURLOPT_PROXYUSERPWD => "xxx:xxx",
]);
$whois = Whois::create($loader);
var_dump([
    '404.run' => $whois->loadDomainInfo('404.run')
]);
```

* Got this output (no falatls or exception):
array(1) {
  ["404.run"]=>
  object(Iodev\Whois\Modules\Tld\DomainInfo)#876 (3) {
    ["response":"Iodev\Whois\Modules\Tld\DomainInfo":private]=>
    object(Iodev\Whois\Modules\Tld\DomainResponse)#875 (4) {
      ["domain":"Iodev\Whois\Modules\Tld\DomainResponse":private]=>
      string(7) "404.run"
      ["query":"Iodev\Whois\Response":private]=>
      string(9) "404.run
"
      ["text":"Iodev\Whois\Response":private]=>
      string(5339) "Domain Name: 404.run
Registry Domain ID: c5c41a0aff2b4e4a9eda8a540547541a-DONUTS
Registrar WHOIS Server: who.godaddy.com/
Registrar URL: http://www.godaddy.com/domains/search.aspx?ci=8990
Updated Date: 2018-10-03T20:32:51Z
Creation Date: 2015-08-19T20:32:17Z
Registry Expiry Date: 2019-08-19T20:32:17Z
Registrar: GoDaddy.com, LLC
Registrar IANA ID: 146
Registrar Abuse Contact Email: abuse@godaddy.com
Registrar Abuse Contact Phone: +1.4806242505
Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
Domain Status: clientRenewProhibited https://icann.org/epp#clientRenewProhibited
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited
Registry Registrant ID: REDACTED FOR PRIVACY
Registrant Name: REDACTED FOR PRIVACY
Registrant Organization: 
Registrant Street: REDACTED FOR PRIVACY
Registrant City: REDACTED FOR PRIVACY
Registrant State/Province: California
Registrant Postal Code: REDACTED FOR PRIVACY
Registrant Country: US
Registrant Phone: REDACTED FOR PRIVACY
Registrant Phone Ext: REDACTED FOR PRIVACY
Registrant Fax: REDACTED FOR PRIVACY
Registrant Fax Ext: REDACTED FOR PRIVACY
Registrant Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Registry Admin ID: REDACTED FOR PRIVACY
Admin Name: REDACTED FOR PRIVACY
Admin Organization: REDACTED FOR PRIVACY
Admin Street: REDACTED FOR PRIVACY
Admin City: REDACTED FOR PRIVACY
Admin State/Province: REDACTED FOR PRIVACY
Admin Postal Code: REDACTED FOR PRIVACY
Admin Country: REDACTED FOR PRIVACY
Admin Phone: REDACTED FOR PRIVACY
Admin Phone Ext: REDACTED FOR PRIVACY
Admin Fax: REDACTED FOR PRIVACY
Admin Fax Ext: REDACTED FOR PRIVACY
Admin Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Registry Tech ID: REDACTED FOR PRIVACY
Tech Name: REDACTED FOR PRIVACY
Tech Organization: REDACTED FOR PRIVACY
Tech Street: REDACTED FOR PRIVACY
Tech City: REDACTED FOR PRIVACY
Tech State/Province: REDACTED FOR PRIVACY
Tech Postal Code: REDACTED FOR PRIVACY
Tech Country: REDACTED FOR PRIVACY
Tech Phone: REDACTED FOR PRIVACY
Tech Phone Ext: REDACTED FOR PRIVACY
Tech Fax: REDACTED FOR PRIVACY
Tech Fax Ext: REDACTED FOR PRIVACY
Tech Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Name Server: ns01.cashparking.com
Name Server: ns02.cashparking.com
DNSSEC: unsigned
URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of WHOIS database: 2019-05-11T14:54:54Z <<<

For more information on Whois status codes, please visit https://icann.org/epp

Terms of Use: Donuts Inc. provides this Whois service for information purposes, and to assist persons in obtaining information about or related to a domain name registration record. Donuts does not guarantee its accuracy. Users accessing the Donuts Whois service agree to use the data only for lawful purposes, and under no circumstances may this data be used to: a) allow, enable, or otherwise support the transmission by e-mail, telephone, or facsimile of mass unsolicited, commercial advertising or solicitations to entities other than the registrar’s own existing customers and b) enable high volume, automated, electronic processes that send queries or data to the systems of Donuts or any ICANN-accredited registrar, except as reasonably necessary to register domain names or modify existing registrations. When using the Donuts Whois service, please consider the following: The Whois service is not a replacement for standard EPP commands to the SRS service. Whois is not considered authoritative for registered domain objects. The Whois service may be scheduled for downtime during production or OT&E maintenance periods. Queries to the Whois services are throttled. If too many queries are received from a single IP address within a specified time, the service will begin to reject further queries for a period of time to prevent disruption of Whois service access. Abuse of the Whois system through data mining is mitigated by detecting and limiting bulk query access from single sources. Where applicable, the presence of a [Non-Public Data] tag indicates that such data is not made publicly available due to applicable data privacy laws or requirements. Should you wish to contact the registrant, please refer to the Whois records available through the registrar URL listed above. Access to non-public data may be provided, upon request, where it can be reasonably confirmed that the requester holds a specific legitimate interest and a proper legal basis for accessing the withheld data. Access to this data can be requested by submitting a request via the form found at https://donuts.domains/about/policies/whois-layered-access/ Donuts Inc. reserves the right to modify these terms at any time. By submitting this query, you agree to abide by this policy.
"
      ["host":"Iodev\Whois\Response":private]=>
      string(13) "whois.nic.run"
    }
    ["data":"Iodev\Whois\Modules\Tld\DomainInfo":private]=>
    array(8) {
      ["domainName"]=>
      string(7) "404.run"
      ["whoisServer"]=>
      string(0) ""
      ["nameServers"]=>
      array(2) {
        [0]=>
        string(20) "ns01.cashparking.com"
        [1]=>
        string(20) "ns02.cashparking.com"
      }
      ["creationDate"]=>
      int(1440016337)
      ["expirationDate"]=>
      int(1566246737)
      ["owner"]=>
      string(20) "REDACTED FOR PRIVACY"
      ["registrar"]=>
      string(16) "GoDaddy.com, LLC"
      ["states"]=>
      array(4) {
        [0]=>
        string(22) "clientdeleteprohibited"
        [1]=>
        string(21) "clientrenewprohibited"
        [2]=>
        string(24) "clienttransferprohibited"
        [3]=>
        string(22) "clientupdateprohibited"
      }
    }
    ["parserType":"Iodev\Whois\Modules\Tld\DomainInfo":private]=>
    string(6) "common"
  }
}
